---
development:
  GET_GEM_LIST: 100_get_gem_list
  GET_GEM_BASIC_INFO: 200_get_gem_basic_info
  PARSE_BASIC_INFO: 300_parse_basic_info
  MATCH_GITHUB_LIST: 400_match_github_list
  GET_RAW_RESPONSES: 500_get_raw_responses
  PATCH_ERROR_RESPONSES: 600_patch_error_responses
  RELATIONL_RESPONSES: 700_relational_responses
  PRUNED_WITH_CUTOFF_TIME: 800_pruned_with_cutoff_time
  GATHER_FEATURES: 900_gather_features
  RESPONSES_CONTRIBUTORS_LIST: repos_raw_responses_contributors_list
  RESPONSES_META: repos_raw_responses_repo_meta
  RESPONSES_COMMITS: repos_raw_responses_commits
  RESPONSES_ISSUES: repos_raw_responses_issues
  RESPONSES_TOTAL_DOWNLOAD_TREND: gems_raw_responses_total_download_trend
  RESPONSES_DAILY_DOWNLOAD_TREND: gems_raw_responses_daily_download_trend
  RESPONSES_VERSION_DOWNLOADS: gems_raw_responses_version_downloads
  RESPONSES_STARGAZERS: repos_raw_responses_stargazers
  RESPONSES_SUBSCRIBERS: repos_raw_responses_subscribers
  RESPONSES_FORKS: repos_raw_responses_forks
  RELATIONAL_GEMS: rubygems
  RELATIONAL_REPO_META: repos
  RELATIONAL_PROFILES: profiles
  RELATIONAL_COMMITS: commits
  RELATIONAL_ISSUES: issues
  RELATIONAL_DAILY_DOWNLOADS: daily_downloads
  RELATIONAL_VERSIONS: versions
  RELATIONAL_STARGAZERS: stargazers
  RELATIONAL_SUBSCRIBERS: subscribers
  RELATIONAL_FORKS: forks
  RELATIONAL_DOWNLOADS: downloads
  RELATIONAL_GEM_VERSION: gem_versions
  RELATIONAL_GEM_DEPENDENCY: gem_dependencies
  FEATURES: gem_features
  FIRST_DOWNLOAD_AT: '2018-03-31T23:09:04+08:00'
production:
  GET_GEM_LIST: 100_get_gem_list
  GET_GEM_BASIC_INFO: 200_get_gem_basic_info
  PARSE_BASIC_INFO: 300_parse_basic_info
  MATCH_GITHUB_LIST: 400_match_github_list
  GET_RAW_RESPONSES: 500_get_raw_responses
  PATCH_ERROR_RESPONSES: 600_patch_error_responses
  RELATIONL_RESPONSES: 700_relational_responses
  PRUNED_WITH_CUTOFF_TIME: 800_pruned_with_cutoff_time
  GATHER_FEATURES: 900_gather_features
  RESPONSES_CONTRIBUTORS_LIST: repos_raw_responses_contributors_list
  RESPONSES_META: repos_raw_responses_repo_meta
  RESPONSES_COMMITS: repos_raw_responses_commits
  RESPONSES_ISSUES: repos_raw_responses_issues
  RESPONSES_TOTAL_DOWNLOAD_TREND: gems_raw_responses_total_download_trend
  RESPONSES_DAILY_DOWNLOAD_TREND: gems_raw_responses_daily_download_trend
  RESPONSES_VERSION_DOWNLOADS: gems_raw_responses_version_downloads
  RESPONSES_STARGAZERS: repos_raw_responses_stargazers
  RESPONSES_SUBSCRIBERS: repos_raw_responses_subscribers
  RESPONSES_FORKS: repos_raw_responses_forks
  RELATIONAL_GEMS: rubygems
  RELATIONAL_REPO_META: repos
  RELATIONAL_PROFILES: profiles
  RELATIONAL_COMMITS: commits
  RELATIONAL_ISSUES: issues
  RELATIONAL_DAILY_DOWNLOADS: daily_downloads
  RELATIONAL_VERSIONS: versions
  RELATIONAL_STARGAZERS: stargazers
  RELATIONAL_SUBSCRIBERS: subscribers
  RELATIONAL_FORKS: forks
  RELATIONAL_DOWNLOADS: downloads
  RELATIONAL_GEM_VERSION: gem_versions
  RELATIONAL_GEM_DEPENDENCY: gem_dependencies
  FEATURES: gem_features
  FIRST_DOWNLOAD_AT: '2018-03-31T23:09:04+08:00'
