---
development:
  :CONTRIBUTORS_LIST: 'repos_raw_responses_contributors_list'
  :REPO_META: 'repos_raw_responses_repo_meta'
  :COMMITS: 'repos_raw_responses_commits'
  :ISSUES: 'repos_raw_responses_issues'
  :TOTAL_DOWNLOAD_TREND: 'gems_raw_responses_total_download_trend'
  :DAILY_DOWNLOAD_TREND: 'gems_raw_responses_daily_download_trend'
  :VERSION_DOWNLOADS: 'gems_raw_responses_version_downloads'
production:
  :CONTRIBUTORS_LIST: 'repos_raw_responses_contributors_list'
  :REPO_META: 'repos_raw_responses_repo_meta'
  :COMMITS: 'repos_raw_responses_commits'
  :ISSUES: 'repos_raw_responses_issues'
  :TOTAL_DOWNLOAD_TREND: 'gems_raw_responses_total_download_trend'
  :DAILY_DOWNLOAD_TREND: 'gems_raw_responses_daily_download_trend'
  :VERSION_DOWNLOADS: 'gems_raw_responses_version_downloads'
