---
  - REPO_USER: 'thbar'
    REPO_NAME: 'kiba'
    GEM_NAME: 'kiba'
  - REPO_USER: 'NoBetterThan97'
    REPO_NAME: 'FoodNutritionix'
    GEM_NAME: 'foodnutritionix'
  - REPO_USER: 'ISS-SOA'
    REPO_NAME: 'facegroup'
    GEM_NAME: 'facegroup'
  # - REPO_USER: 'elabs'
  #   REPO_NAME: 'econfig'
  #   GEM_NAME: 'econfig'
